# Generated by Django 5.0.2 on 2024-03-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vizag_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(max_length=100)),
                ('Placelocation', models.CharField(max_length=100)),
                ('Placemg_name', models.CharField(max_length=100)),
            ],
        ),
    ]
